version: 1
disable_existing_loggers: false

formatters:
  default:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(filename)s:%(lineno)d - %(funcName)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

  json:
    format: '{"timestamp": "%(asctime)s", "service": "%(name)s", "level": "%(levelname)s", "message": "%(message)s", "file": "%(filename)s", "line": %(lineno)d}'
    datefmt: '%Y-%m-%dT%H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: default
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: detailed
    filename: /app/data/logs/app.log
    maxBytes: 10485760  # 10MB
    backupCount: 5

  discovery_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: detailed
    filename: /app/data/logs/discovery.log
    maxBytes: 10485760
    backupCount: 5

  download_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: detailed
    filename: /app/data/logs/download.log
    maxBytes: 10485760
    backupCount: 5

  parser_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: detailed
    filename: /app/data/logs/parser.log
    maxBytes: 10485760
    backupCount: 5

  web_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: detailed
    filename: /app/data/logs/web.log
    maxBytes: 10485760
    backupCount: 5

loggers:
  discovery:
    level: INFO
    handlers: [console, discovery_file]
    propagate: false

  download:
    level: INFO
    handlers: [console, download_file]
    propagate: false

  parser:
    level: INFO
    handlers: [console, parser_file]
    propagate: false

  web:
    level: INFO
    handlers: [console, web_file]
    propagate: false

root:
  level: INFO
  handlers: [console, file]